services:
  # MySQL Service
  - type: pserv
    name: mysql-db
    env: docker
    plan: starter
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: wordpress
      - key: MYSQL_USER
        value: wordpress
      - key: MYSQL_PASSWORD
        value: MySecurePass123!@#
      - key: MYSQL_ROOT_PASSWORD
        value: RootPass123!@#
    ipAllowList: []

  # WordPress Service
  - type: web
    name: wordpress
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: WORDPRESS_DB_HOST
        fromService:
          type: pserv
          name: mysql-db
          port: 3306
      - key: WORDPRESS_DB_USER
        fromService:
          type: pserv
          name: mysql-db
          envKey: MYSQL_USER
      - key: WORDPRESS_DB_PASSWORD
        fromService:
          type: pserv
          name: mysql-db
          envKey: MYSQL_PASSWORD
      - key: WORDPRESS_DB_NAME
        fromService:
          type: pserv
          name: mysql-db
          envKey: MYSQL_DATABASE
      - key: WORDPRESS_DEBUG
        value: "1"
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content
      sizeGB: 10
    domains:
      - espbot.onrender.com
    dependsOn:
      - mysql-db