databases:
  - name: wordpressdb
    plan: free
    type: mysql
    region: oregon
    databaseName: wordpress
    user: wpuser
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: MYSQL_DATABASE
        fromDatabase:
          name: wordpressdb
          property: database
      - key: MYSQL_USER
        fromDatabase:
          name: wordpressdb
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: wordpressdb
          property: password
      - key: MYSQL_HOST
        fromDatabase:
          name: wordpressdb
          property: host
      - key: DB_PORT
        value: "3306"
      - key: WORDPRESS_CONFIG_EXTRA
        value: |
          define('FORCE_SSL_ADMIN', true);
          define('WP_MEMORY_LIMIT', '256M');
          if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
            $_SERVER['HTTPS'] = 'on';
            define('FORCE_SSL_ADMIN', true);
            define('FORCE_SSL_LOGIN', true);
          }
      - key: WP_DEBUG
        value: "false"
      - key: WP_CACHE
        value: "true"
      - key: WP_AUTO_UPDATE_CORE
        value: "false"
    disk:
      name: wordpress-data
      mountPath: /var/www/html
      sizeGB: 10
    healthCheckPath: /
    numInstances: 1
    domains:
      - espbot.onrender.com