databases:
  - name: wordpress-db
    plan: free
    type: postgres
    region: ohio

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: WORDPRESS_DB_HOST
        value: dpg-cusvgi0gph6c73atsci0-a.ohio-postgres.render.com
      - key: WORDPRESS_DB_USER
        value: wordpress_ygs8_user
      - key: WORDPRESS_DB_NAME
        value: wordpress_ygs8
      - key: WORDPRESS_DB_PASSWORD
        sync: false
      - key: WORDPRESS_DEBUG
        value: "true"
      - key: WORDPRESS_CONFIG_EXTRA
        value: |
          define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']);
          define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1
