databases:
  - name: mysql
    databaseName: wordpress
    user: wordpress
    plan: free
    region: oregon
    type: mysql

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: MYSQL_DATABASE
        fromDatabase:
          name: mysql
          property: database
      - key: MYSQL_USER
        fromDatabase:
          name: mysql
          property: user
      - key: MYSQL_PASSWORD
        fromDatabase:
          name: mysql
          property: password
      - key: MYSQL_HOST
        fromDatabase:
          name: mysql
          property: host
      - key: MYSQL_PORT
        value: "3306"
    disk:
      name: wordpress-data
      mountPath: /var/www/html
      sizeGB: 10
    healthCheckPath: /wp-admin/install.php
    numInstances: 1
    domains:
      - espbot.onrender.com