services:
  - type: web
    name: wordpress
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /wp-admin/install.php
    envVars:
      - key: WORDPRESS_DB_HOST
        value: mysql-db.internal
      - key: WORDPRESS_DB_USER
        value: wordpress
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_PASSWORD
        value: MySecurePass123!@#
      - key: WORDPRESS_DEBUG
        value: "1"
    disk:
      name: wordpress-data
      mountPath: /var/www/html
      sizeGB: 10
    domains:
      - espbot.onrender.com
    dependsOn:
      - mysql-db

  - type: pserv
    name: mysql-db
    env: docker
    plan: free
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: wordpress
      - key: MYSQL_USER
        value: wordpress
      - key: MYSQL_PASSWORD
        value: MySecurePass123!@#
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    ipAllowList: []