services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: WORDPRESS_DB_HOST
        value: wordpress-db.internal
      - key: WORDPRESS_DB_USER
        value: postgres
      - key: WORDPRESS_DB_PASSWORD
        generateValue: true
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DEBUG
        value: "true"
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1

  - type: pserv
    name: wordpress-db
    env: docker
    plan: free
    region: ohio
    image: postgres:15-alpine
    autoDeploy: false
    envVars:
      - key: POSTGRES_DB
        value: wordpress
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
