databases:
  - name: wordpress-db
    plan: free
    type: postgres
    region: ohio
    databaseName: wordpress

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    dependencies:
      - wordpress-db
    envVars:
      - key: PORT
        value: 8080
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
      - key: DATABASE_URL
        fromDatabase:
          name: wordpress-db
          property: connectionString
      - key: WORDPRESS_DEBUG
        value: "true"
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1
