services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: MYSQL_HOST
        value: mysql
      - key: MYSQL_PORT
        value: "3306"
      - key: WP_DEBUG
        value: "true"
    envGroups:
      - name: wordpress-config
    disk:
      name: wordpress-data
      mountPath: /var/www/html
      sizeGB: 10
    healthCheckPath: /wp-admin/install.php
    numInstances: 1
    domains:
      - espbot.onrender.com

  - type: pserv
    name: mysql
    env: docker
    plan: free
    region: oregon
    image:
      url: mysql:8.0
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envGroups:
      - name: wordpress-config