services:
  - type: web
    name: wordpress
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    domains:
      - espbot.onrender.com
    envVars:
      - key: WORDPRESS_DB_HOST
        value: mysql-db.internal:3306
      - key: WORDPRESS_DB_USER
        value: wordpress
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_PASSWORD
        value: MySecurePass123!@#
      - key: WP_DEBUG
        value: "true"
    disk:
      name: wordpress-data
      mountPath: /var/www/html
      sizeGB: 10
    dependsOn:
      - mysql-db

  - type: pserv
    name: mysql-db
    env: docker
    plan: free
    region: oregon
    image:
      url: mysql:8.0
    dockerCommand: --default-authentication-plugin=mysql_native_password
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: wordpress
      - key: MYSQL_USER
        value: wordpress
      - key: MYSQL_PASSWORD
        value: MySecurePass123!@#
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
    ipAllowList: []