databases:
  - name: wordpress-db
    plan: free
    databaseName: wordpress
    ipAllowList: []

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: wordpress-db
          property: connectionString
      - key: WORDPRESS_DEBUG
        value: "true"
      - key: WP_ENV
        value: "production"
      - key: WORDPRESS_CONFIG_EXTRA
        value: |
          define('WP_HOME', 'https://' . $_SERVER['HTTP_HOST']);
          define('WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST']);
          define('FORCE_SSL_ADMIN', true);
          $_SERVER['HTTPS'] = 'on';
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1
