services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: wordpress-db
          property: connectionString
      - key: WORDPRESS_DEBUG
        value: "true"
      - key: WP_ENV
        value: "production"
      - key: WORDPRESS_AUTH_KEY
        generateValue: true
      - key: WORDPRESS_SECURE_AUTH_KEY
        generateValue: true
      - key: WORDPRESS_LOGGED_IN_KEY
        generateValue: true
      - key: WORDPRESS_NONCE_KEY
        generateValue: true
      - key: WORDPRESS_AUTH_SALT
        generateValue: true
      - key: WORDPRESS_SECURE_AUTH_SALT
        generateValue: true
      - key: WORDPRESS_LOGGED_IN_SALT
        generateValue: true
      - key: WORDPRESS_NONCE_SALT
        generateValue: true

databases:
  - name: wordpress-db
    plan: free
    databaseName: wordpress
    ipAllowList: []
