databases:
  - name: wordpress-db
    plan: free
    type: postgres
    region: ohio
    databaseName: wordpress

services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    region: ohio
    buildCommand: docker build -t wordpress-app .
    startCommand: /usr/local/bin/start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: wordpress-db
          property: connectionString
      - key: WORDPRESS_DEBUG
        value: "true"
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content/uploads
      sizeGB: 1

  - type: pserv
    name: wordpress-db
    env: docker
    plan: free
    region: ohio
    image: postgres:15-alpine
    envVars:
      - key: POSTGRES_DB
        value: wordpress
      - key: POSTGRES_USER
        value: wordpress
      - key: POSTGRES_PASSWORD
        generateValue: true
